kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/${NAMESPACE}/deploymentconfigs/docker-mautic-noroot
  name: ${INSTANCE}-mautic
  namespace: ${NAMESPACE}
  labels:
    app: ${INSTANCE}-mautic
    app.kubernetes.io/component: ${INSTANCE}-mautic
    app.kubernetes.io/instance: ${INSTANCE}-mautic
    app.openshift.io/runtime-namespace: ${NAMESPACE}
spec:
  strategy:
    type: Recreate
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: ${INSTANCE}-mautic
    deploymentconfig: ${INSTANCE}-mautic
  template:
    metadata:
      labels:
        app: ${INSTANCE}-mautic
        deploymentconfig: ${INSTANCE}-mautic
    spec:
      volumes:
        - name: ${INSTANCE}-mautic-config
          persistentVolumeClaim:
            claimName: ${INSTANCE}-mautic-config
        - name: ${INSTANCE}-mautic-media
          persistentVolumeClaim:
            claimName: ${INSTANCE}-mautic-media
      containers:
        - name: docker-mautic-noroot
          image: >-
            docker-remote.artifacts.developer.gov.bc.ca/jeremyvernon/docker-mautic-noroot:v02
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: HASH_KEY
              value: ${HASH_KEY}
            - name: SITE_URL
              value: http:/${INSTANCE}-mautic-${NAMESPACE}.apps.silver.devops.gov.bc.ca
            - name: MAILER_FROM_NAME
              value: ${MAILER_FROM_NAME}
            - name: MAILER_FROM_EMAIL
              value: ${MAILER_FROM_EMAIL}
            - name: MAILER_HOST
              value: ${MAILER_HOST}
            - name: MAILER_USER
              value: ${MAILER_USER}
            - name: MAILER_PORT
              value: ${MAILER_PORT}
            - name: MAILER_ENCRYPTION
              value: ${MAILER_ENCRYPTION}
            - name: MAILER_AUTH_MODE
              value: ${MAILER_AUTH_MODE}
            - name: MAUTIC_DB_HOST
              value: ${INSTANCE}-mautic-db
            - name: MAUTIC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE}-mautic-db
                  key: database-user
            - name: MAUTIC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE}-mautic-db
                  key: database-password
            - name: MAUTIC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: ${INSTANCE}-mautic-db
                  key: database-name
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler