kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  selfLink: /api/v1/namespaces/b07dd3-test/secrets/${INSTANCE}-mautic-db
  resourceVersion: '308544646'
  name: ${INSTANCE}-mautic-db
  namespace: ${NAMESPACE}
data:
  database-name: ${DATABASE_NAME}
  database-password: ${DATABASE_PASSWORD}
  database-root-password: ${DATABASE_ROOT_PASSWORD}
  database-user: ${DATABASE_USER}
type: Opaque
